version: "1.0"
name: "basecode"
services:
  database:
    image: postgres:11.0
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    expose:
      - "${DB_PORT}"